### ISSUE TITLE
Schemagen with TEI

### ISSUE THREAD

**Issue by orazionelson** [adamretter/prosemirror-xml-schemagen#1]
Hello,
i'm trying to generate a prosemirror schema from TEI, i tried with tei_lite and tei_minimal but the error is always the same: **Could not find root element in Schema named: TEI**
(i tried with alla xsd groups at this url: https://www.tei-c.org/release/xml/tei/custom/schema/xsd/ )

`me@linux:/var/www/html/prosemirror/prosemirror-xml-schemagen$ java -jar target/scala-2.12/prosemirror-xml-schemagen-assembly-0.1.jar tei_minimal.xsd TEI > tei.txt
java.lang.IllegalArgumentException: Could not find root element in Schema named: TEI
	at com.evolvedbinary.prosemirror.xmlschemagen.SchemaGen.toProseMirrorSchema(SchemaGen.scala:55)
	at com.evolvedbinary.prosemirror.xmlschemagen.CmdLine$.$anonfun$main$2(App.scala:83)
	at scala.util.Either.flatMap(Either.scala:338)
	at com.evolvedbinary.prosemirror.xmlschemagen.CmdLine$.$anonfun$main$1(App.scala:82)
	at scala.util.Either.flatMap(Either.scala:338)
	at com.evolvedbinary.prosemirror.xmlschemagen.CmdLine$.main(App.scala:81)
	at com.evolvedbinary.prosemirror.xmlschemagen.CmdLine.main(App.scala)
`

**Comment by adamretter** [comment]
This project was an experiment which I never completed, so I would not expect it to work
